### ISSUE TITLE
PlatformException when calling service.characteristics() with SimulatedCharacteristic

### ISSUE THREAD

**Issue by GurgenHOVH** [Polidea/blemulator_flutter#66]
```
I/SimulatedAdapter(28778): discoverAllServicesAndCharacteristicsForDevice
D/com.polidea.flutter_ble_lib.FlutterBleLibPlugin(28778): on native side observed method: characteristicsForService
I/SimulatedAdapter(28778): discoverAllServicesAndCharacteristicsForDevice
E/MethodChannel#flutter_ble_lib(28778): Failed to handle method call
E/MethodChannel#flutter_ble_lib(28778): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object[] java.util.List.toArray(java.lang.Object[])' on a null object reference
E/MethodChannel#flutter_ble_lib(28778): 	at com.polidea.blemulator.SimulatedAdapter.getCharacteristicsForService(SimulatedAdapter.java:328)
E/MethodChannel#flutter_ble_lib(28778): 	at com.polidea.flutter_ble_lib.delegate.DiscoveryDelegate.getCharacteristicsForService(DiscoveryDelegate.java:152)
E/MethodChannel#flutter_ble_lib(28778): 	at com.polidea.flutter_ble_lib.delegate.DiscoveryDelegate.onMethodCall(DiscoveryDelegate.java:72)
E/MethodChannel#flutter_ble_lib(28778): 	at com.polidea.flutter_ble_lib.FlutterBleLibPlugin.onMethodCall(FlutterBleLibPlugin.java:96)
E/MethodChannel#flutter_ble_lib(28778): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#flutter_ble_lib(28778): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#flutter_ble_lib(28778): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/MethodChannel#flutter_ble_lib(28778): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_ble_lib(28778): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter_ble_lib(28778): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#flutter_ble_lib(28778): 	at android.app.ActivityThread.main(ActivityThread.java:6863)
E/MethodChannel#flutter_ble_lib(28778): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_ble_lib(28778): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/MethodChannel#flutter_ble_lib(28778): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
D/com.polidea.flutter_ble_lib.FlutterBleLibPlugin(28778): on native side observed method: characteristicsForService
I/SimulatedAdapter(28778): discoverAllServicesAndCharacteristicsForDevice
E/MethodChannel#flutter_ble_lib(28778): Failed to handle method call
E/MethodChannel#flutter_ble_lib(28778): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object[] java.util.List.toArray(java.lang.Object[])' on a null object reference
E/MethodChannel#flutter_ble_lib(28778): 	at com.polidea.blemulator.SimulatedAdapter.getCharacteristicsForService(SimulatedAdapter.java:328)
E/MethodChannel#flutter_ble_lib(28778): 	at com.polidea.flutter_ble_lib.delegate.DiscoveryDelegate.getCharacteristicsForService(DiscoveryDelegate.java:152)
E/MethodChannel#flutter_ble_lib(28778): 	at com.polidea.flutter_ble_lib.delegate.DiscoveryDelegate.onMethodCall(DiscoveryDelegate.java:72)
E/MethodChannel#flutter_ble_lib(28778): 	at com.polidea.flutter_ble_lib.FlutterBleLibPlugin.onMethodCall(FlutterBleLibPlugin.java:96)
E/MethodChannel#flutter_ble_lib(28778): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#flutter_ble_lib(28778): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#flutter_ble_lib(28778): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/MethodChannel#flutter_ble_lib(28778): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_ble_lib(28778): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter_ble_lib(28778): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#flutter_ble_lib(28778): 	at android.app.ActivityThread.main(ActivityThread.java:6863)
E/MethodChannel#flutter_ble_lib(28778): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_ble_lib(28778): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/MethodChannel#flutter_ble_lib(28778): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/gioteas.tefori(28778): Waiting for a blocking GC ProfileSaver
I/gioteas.tefori(28778): WaitForGcToComplete blocked ProfileSaver on ProfileSaver for 12.000ms
```

**Comment by mikolak** [comment]
Hi, @gurgenDP!

Thanks for the issue! Could you confirm if this scenario crashed BLEmulator only on Android or does it occur on iOS as well?

Could you show me how the peripheral looks like?

**Comment by GurgenHOVH** [comment]
Hello @mikolak. Thanks for the BLE plugin and emulator.

This happens only on Android, in my case real device running Android 9. So far iOS is working good. 

Here is the peripheral snippet. 
``` dart
class InfuserPeripheral extends SimulatedPeripheral {
  final String id;
  final String name;
  final String localName;

  InfuserPeripheral({this.id, this.name, this.localName = ""})
      : super(
            id: id,
            name: name,
            advertisementInterval: Duration(milliseconds: 800),
            services: [
              SimulatedService(
                  uuid: "8ba16c63-1810-c6d2-1a3d-09eb265d0000",
                  isAdvertised: true,
                  characteristics: [
                    Control(
                        uuid: "8ba16c63-1810-c6d2-1a3d-09eb265d0001",
                        convenienceName: "Control")
                  ],
                  convenienceName: "Teforia Service")
            ]) {
    scanInfo.localName = localName;
    scanInfo.isConnectable = true;
    scanInfo.serviceUuids = ['8ba16c63-1810-c6d2-1a3d-09eb265d0000'];
  }

  @override
  Future<bool> onConnectRequest() async {
    await Future.delayed(Duration(milliseconds: 200));
    return super.onConnectRequest();
  }
}

/// Teforia BLE device single Characteristic Simulation.
class Control extends SimulatedCharacteristic {
  Control({@required String uuid, String convenienceName})
      : super(
            uuid: uuid,
            isReadable: true,
            isWritableWithResponse: true,
            isWritableWithoutResponse: false,
            isNotifying: true,
            isNotifiable: true,
            value: Uint8List.fromList([0]),
            convenienceName: convenienceName);

  // Whatever the BLE server sends Infuser Status notifications or not
  bool isSendingInfuserStatus = false;

  @override
  Future<void> write(Uint8List value) async {
    await super.write(value);

    // Parse the incoming data and respond
    await triggerCharacteristicWrite(this, value);

    return;
  }

  @override
  Future<Uint8List> read() {
    return super.read();
  }
}
```

Thanks!

**Comment by mikolak** [comment]
Thanks for the snippet! I've reproduced the issue and am working on it. I'll work on the solution tomorrow, hopefully I'll be able to release a patched version tomorrow as well.

**Comment by GurgenHOVH** [comment]
Thanks @mikolak . Can you also update the version of FlutterBleLib tomorrow? There was a blocking issue on FlutterBleLib, which you guys fixed already. blemulator_flutter depends on hardcoded version .dev-6 of FlutterBleLib. 

Thank you very much.

**Comment by mikolak** [comment]
I've uploaded new versions of both libraries, FlutterBleLib 2.0.0-dev.7 and BLEmulator 1.0.0-dev.5.
